api/urls.py
# Copyright 2009 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.conf.urls.defaults import *

urlpatterns = patterns('',
    (r'^$',
        'django.views.generic.simple.redirect_to',
        {'url': '/docs'}),
    (r'^api(?P<the_rest>/.*)$',
        'django.views.generic.simple.redirect_to',
        {'url': '%(the_rest)s'}),
    (r'^keys$', 'api.views.api_keys'),
    (r'^keys/(?P<consumer_key>\w+)$', 'api.views.api_key'),
    (r'^key$', 'api.views.api_key_legacy'),
    (r'^tokens', 'api.views.api_tokens'),
    (r'^docs$', 'api.views.api_docs'),
    (r'^docs/(?P<doc>\w+)$', 'api.views.api_doc'),
    (r'^json', 'api.views.api_call'),
    (r'^loaddata', 'api.views.api_loaddata'),
    (r'^cleardata', 'api.views.api_cleardata'),
    (r'^request_token', 'api.views.api_request_token'),
    (r'^authorize', 'api.views.api_authorize'),
    (r'^access_token', 'api.views.api_access_token'),
    (r'^sms_receive/(?P<vendor_secret>.*)$', 'api.views.api_vendor_sms_receive'),
    (r'^process_queue$', 'api.views.api_vendor_queue_process'),
    (r'^xmlrpc', 'api.views.api_xmlrpc'),
)


handler404 = 'common.views.common_404'
handler500 = 'common.views.common_500'

sample_project/batchimport/urls.py
"""
URLConf for Django batch import and update.

If the default behavior of the batchimport views is acceptable to
you, simply use a line like this in your root URLConf to set up the
default URLs for batchimport:

    (r'^batchimport/', include('batchimport.urls')),

But if you'd like to customize the behavior (e.g., by passing extra
arguments to the various views) or split up the URLs, feel free to set
up your own URL patterns for these views instead.

"""


from django.conf.urls.defaults import *

from batchimport.views import import_start, import_options, import_execute

urlpatterns = patterns('',
                       # Activation keys get matched by \w+ instead of the more specific
                       # [a-fA-F0-9]{40} because a bad activation key should still get to the view;
                       # that way it can return a sensible "invalid key" message instead of a
                       # confusing 404.
						url(r'^import_start/$',
							import_start,
							name='batchimport_import_start'),
						url(r'^import_options/$',
                           import_options,
                           name='batchimport_import_options'),
                       url(r'^import_execute/$',
                           import_execute,
                           name='batchimport_import_execute'),
                       )

sample_project/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^batchimport/', include('batchimport.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/(.*)', admin.site.root),
    (r'^batchimport/', include('batchimport.urls')),
)

sample_project/batchimport/forms.py
from django import forms
from batchimport.util import get_model_list, get_column_choice_list, get_model_fields
import batchimport.batchimport_settings


import_model_list = get_model_list()

class UploadImportFileForm(forms.Form):
	model_for_import = forms.ChoiceField(import_model_list, label='What are you importing?')
	import_file = forms.FileField(label='Select your XLS file:')

class ImportOptionsForm(forms.Form):
	show_successful_imports = forms.BooleanField(initial=batchimport.batchimport_settings.BATCH_IMPORT_SHOW_SUCCESSFUL_IMPORTS, required=False)
	show_successful_updates = forms.BooleanField(initial=batchimport.batchimport_settings.BATCH_IMPORT_SHOW_SUCCESSFUL_UPDATES, required=False)
	show_errors = forms.BooleanField(initial=batchimport.batchimport_settings.BATCH_IMPORT_SHOW_ERRORS, required=False)
	stop_on_first_error = forms.BooleanField(initial=batchimport.batchimport_settings.BATCH_IMPORT_STOP_ON_FIRST_ERROR, required=False)
	update_dupes = forms.BooleanField(initial=batchimport.batchimport_settings.BATCH_IMPORT_UPDATE_DUPS, required=False)
	start_row = forms.IntegerField(initial=batchimport.batchimport_settings.BATCH_IMPORT_START_ROW, required=False)
	end_row = forms.IntegerField(initial=batchimport.batchimport_settings.BATCH_IMPORT_END_ROW, required=False)
	def __init__(self, model_for_import, save_file_name, *args, **kwargs):
		super(ImportOptionsForm, self).__init__(*args, **kwargs)
		self.process_options = {}
		
		# Initialize several lists to be used later...
		self.model_field_names = []
		self.relation_info_dict = {}
		
		# Get a list of columns from the uploaded spreadsheet.
		# This will be either a list of example values or a list
		# of column headers.
		xls_column_option_list = get_column_choice_list(save_file_name)
		
		# Get a list of field names from the selected model
		# for import.
		self.mapping_only = False
		
		model_list = []
		if 'relation' in model_for_import:
			import_model_info_list = model_for_import.split('%')
			model_list.append(import_model_info_list[0])
			if len(import_model_info_list) > 1:
				model_list.append(import_model_info_list[2])
			self.mapping_only = True
		else:
			model_list = [model_for_import]
		
		for model_name in model_list:

			# In this field_tuple_list is the following for each field in the current model:
			# - field.name: The name of the field.
			# - related_model_app_name: Name of the app for any 
			#		related model name (if there is one).
			# - related_model_name: Name of the related model
			#		itself (again, if there is one).
			# - related_model_field_name_list: List of fields on the
			#		related model (for mapping the current model's 
			#		field to the related model).
			model_field_tuple_list = get_model_fields(model_name, self.mapping_only)
			
			# Iterate over this field_tuple_list and create a form field 
			# for each of the following FOR EACH FIELD in the model:
			#		- xls_columns_available (list of columns from the spreadsheet)
			#		- default_value_field (default value if none is in the spreadsheet)
			#		- related_field_mapping (list of fields on the related model)
			#		- id_field (to specify whether this field is in the group of
			#			fields for this model that together can be used to uniquely
			#			identify an instance of the model.
			for field_tuple in model_field_tuple_list:
				base_field_name = field_tuple[0]
				full_field_name = model_name + '.' + base_field_name
				
				# XLS column name list for this field.
				xls_column_field_name = full_field_name + '-xls_column'
				self.model_field_names.append(xls_column_field_name)
				initial_value = self._get_initial_value(xls_column_option_list, base_field_name)
				self.fields[xls_column_field_name] = forms.ChoiceField(xls_column_option_list, label='Spreadsheet column:', required=False, initial=initial_value)

				# ID selection checkmark (see template for example)
				is_id_field_name = full_field_name + '-is_id_field'
				self.model_field_names.append(is_id_field_name)
				if not self.mapping_only:
					self.fields[is_id_field_name] = forms.BooleanField(required=False,initial=True)
				else:
					self.fields[is_id_field_name] = forms.BooleanField(required=False,initial=False)
				
				if not self.mapping_only:
					related_model_app_name = field_tuple[1]
					related_model_name = field_tuple[2]
					field_mapping_list = field_tuple[3]
					
					# Get list of fields on the related model as needed.
					related_field_choice_list = []
					if field_mapping_list:
						for related_field_name in field_mapping_list:
							related_field_choice_list.append((related_field_name, related_field_name))
					self.relation_info_dict[full_field_name] = (related_model_app_name, 
															    related_model_name,
															    related_field_choice_list)
		
					# Default value form field.
					default_value_field_name = full_field_name + '-default_value'
					self.model_field_names.append(default_value_field_name)
					self.fields[default_value_field_name] = forms.CharField(label="Default value", max_length=100, required=False)
					
					# List of fields on the related model on which to map this field.
					mapping_choice_field_name = full_field_name + '-mapping_choice'
					self.model_field_names.append(mapping_choice_field_name)
					self.fields[mapping_choice_field_name] = forms.ChoiceField(related_field_choice_list, label='Related model field mapping', required=False)
			self.import_info_dict = self.get_import_info_dict()
			
	def get_import_info_dict(self):
		import_info_dict = {}
		for field_name in self.model_field_names:
			field_name_parts = field_name.split('.')
			model_name = field_name_parts[-2]
			base_field_name = field_name_parts[-1].split('-')[0]
			if not model_name in import_info_dict.keys():
				import_info_dict[model_name] = {}
			model_field_dict = import_info_dict[model_name]
			if not base_field_name in model_field_dict.keys():
				model_field_dict[base_field_name] = []
			field_list = model_field_dict[base_field_name]
			field_list.append(self[field_name])
		return import_info_dict
	
	def get_process_options_dict(self):
		if not self.process_options:
			process_options = {}
			process_options['show_successful_imports'] = self['show_successful_imports']
			process_options['show_successful_updates'] = self['show_successful_updates']
			process_options['show_errors'] = self['show_errors']
			process_options['stop_on_first_error'] = self['stop_on_first_error']
			process_options['update_dupes'] = self['update_dupes']
			process_options['start_row'] = self['start_row']
			process_options['end_row'] = self['end_row']
			self.process_options = process_options
		return self.process_options
		
	def _get_initial_value(self, xls_column_option_list, field_name):
		if field_name[-1] == '*':
			field_name = ''.join(field_name[:-1])
		choice_index = -1
		for item in xls_column_option_list:
			choice = item[1]
			if field_name.lower() == choice.lower():
				choice_index = item[0]
				break
		return str(choice_index)

templates/batchimport/options.html
<html>
<body>
<form id='import_execute_form' action="{% url batchimport_import_options %}" method="POST">
{% if form.mapping_only %}

<h1>Batch Relationship Mapping</h1>
<br/>You've chosen to import relationship data between two types of entities in the system (that 
certain students are associated to certain teachers, for example). <br/><br/>It is assumed that
each row in your uploaded spreadsheet or comma-separated (CSV) file represents enough
information to uniquely identify two instances of the types of entities you are choosing 
to relate.<br/><br/>
Please note that in order for your import to be successful, both of these two entities must ALREADY be
in the system (previously imported or manually added).<br/><br/>
<h2>Instructions:</h2>
For each entity type below, do the following:
<ol>
	<li>Select an appropriate column from the uploaded XLS/CSV file corresponding to the 
	field on the entity (the name on the left).</li>
    <li>Select one or more fields you would like to have the system use to uniquely
	identify the exact instance of the entity by clicking the <b>Is Identity</b> check box for that field.
	</li>
</ol>
<br/>For example, you might check the <b>Is Identity</b> checkbox for <i>first_name</i>, <i>last_name</i>,
    and <i>phone</i> if you thought that information would be enough to uniquely identify a person. As another
    example, if you already have a unique ID for your data, just click the checkbox for that field.<br/><br/>
	{% for model_name, field_dict in form.import_info_dict.items %}
        <h2>{{ model_name }}</h2>
		<table>
			<tr>
				<th>Field Name</th>
				<th>Spreadsheet Column</th>
				<th>Is Identity</th>
			</tr>
			  {% for field_name, field_list in field_dict.items %}
			<tr>
				<td>{{ field_name }}</td>
				{% for field in field_list %}
				<div class="fieldWrapper">
				<td>{{ field }}</td>
				</div>
				{% endfor %}
			</tr>
			{% endfor %}
	    </table><br/>
    {% endfor %}

{% else %}
<h1>Batch Data Import/Update</h1>
<br/>You've chosen to upload data to batch import for a specific type of entity 
(multiple teachers at one time, for example).<br/><br/>
<h2>Instructions:</h2>
Please do the following for each field (on the left) in the table below:
<ol>
    <li>Select an appropriate column from the uploaded XLS/CSV file corresponding to the 
    field on the entity (the name on the left).</li>
    <li>Each row in your spreadsheet or CSV file is assumed to represent a single instance of the
	entity for which you are importing data. If that instance is already in the database, the system
	will automatically update it. In order to do so, it must have a way to uniquely identify the
	item. For each field that can be used (alone or together) to uniquely identify a specific instance,
	click the <b>Is Identity</b> checkbox. By default all are checked, indicating that all fields from the
	spreadsheet must match all corresponding fields in the database for the two to represent the 
	same item.</li>
    <li>For each field for which a given spreadsheet row may not have data, you may enter a default value
	in the input box labeled <b>Default Value</b>.</li>
    <li>In the case where a given field represents another entity already in the database (for example
	if your <i>teacher</i> instance is associated with a specific <i>school</i> instance) the system must know how to 
	find the related object. You don't have to know ahead of time which fields are like this. If a given
	field represents related object, the drop-down under <b>Mapping Field</b> is filled with fields for the related 
	entity (all the fields on the <i>school</i> object, to continue our example). From this drop-down select the
	field which the system should use to find the object using the value found in your spreadsheet.</li>
    <li>Once done, click on the <b>Submit</b> button at the bottom of the page.</li>
</ol><br/>


    {% for model_name, field_dict in form.import_info_dict.items %}
        <h2>{{ model_name }}</h2>
    <table>
        <tr>
            <th>Field Name<br/><small>*=required</small></th>
            <th>Spreadsheet Column</th>
            <th>Is Identity</th>
            <th>Default Value</th>
            <th>Mapping Field</th>
        </tr>
          {% for field_name, field_list in field_dict.items %}
        <tr>
            <td>{{ field_name }}</td>
            {% for field in field_list %}
            <div class="fieldWrapper">
            <td>{{ field }}</td>
            </div>
            {% endfor %}
        </tr>
        {% endfor %}
    </table><br/><br/><br/><br/>
        {% endfor %}
	{% endif %}

<h2>Options</h2>
    <div class="fieldWrapper">
        {{ form.show_successful_imports.errors }}
        <label for="id_show_successful_imports">{{ form.show_successful_imports.label }}</label>
        {{ form.show_successful_imports }}
    </div>
    <div class="fieldWrapper">
        {{ form.show_successful_updates.errors }}
        <label for="id_show_successful_imports">{{ form.show_successful_updates.label }}</label>
        {{ form.show_successful_updates }}
    </div>
    <div class="fieldWrapper">
        {{ form.show_errors.errors }}
        <label for="id_show_successful_imports">{{ form.show_errors.label }}</label>
        {{ form.show_errors }}
    </div>
    <div class="fieldWrapper">
        {{ form.stop_on_first_error.errors }}
        <label for="id_show_successful_imports">{{ form.stop_on_first_error.label }}</label>
        {{ form.stop_on_first_error }}
    </div>
    <div class="fieldWrapper">
        {{ form.update_dupes.errors }}
        <label for="id_show_successful_imports">{{ form.update_dupes.label }}</label>
        {{ form.update_dupes }}
    </div>
    <div class="fieldWrapper">
        {{ form.start_row.errors }}
        <label for="id_show_successful_imports">{{ form.start_row.label }}</label>
        {{ form.start_row }}
    </div>
    <div class="fieldWrapper">
        {{ form.end_row.errors }}
        <label for="id_show_successful_imports">{{ form.end_row.label }}</label>
        {{ form.end_row }}
    </div>

	<input type="submit" value="Submit" />
</form>

</body>
</html>

templates/batchimport/processing.html
<html>
<body>
Processing. Please wait...
<form id='import_execute_form' action="{% url batchimport_import_execute %}" method="POST">
</form>

<SCRIPT LANGUAGE="JavaScript">
window.location="{% url batchimport_import_execute %}";
</SCRIPT>

</body>
</html>

templates/batchimport/results.html
<html>
<body>
<h1>RESULTS FOR IMPORT OF {{ model_for_import }} DATA:</h1>
Rows in spreadsheet: {{ num_rows_in_spreadsheet }}<br/>
User specified start row: {{ start_row }}<br/>
User specified end row: {{ end_row }}<br/>
<br/>
<h2>Summary</h2>
Number of rows successfully processed: {{ num_rows_processed }}<br/>
Number of rows imported: {{ num_items_imported }}<br/>
Number of rows updated: {{ num_items_updated }}<br/>
Number of errors: {{ num_errors }}<br/>
<br/>
<br/>
<h2>Details</h2>
Combined Results (All Messages in Order):<br/>
{% for result in combined_results_messages %}
{{ result }}<br/>
{% endfor %}
<br/><br/>
Imports Only:<br/>
{% for result in import_results_messages %}
{{ result }}<br/>
{% endfor %}
<br/><br/>
Updates Only:<br/>
{% for result in update_results_messages %}
{{ result }}<br/>
{% endfor %}
<br/><br/>
Errors Only:<br/>
{% for result in error_results_messages %}
{{ result }}<br/>
{% endfor %}
<br/><br/>

</body>
</html>

templates/batchimport/start.html
<html>
<body>

{% if form.errors %}
<p>{{ form.errors }}</p>
{% endif %}
<form enctype="multipart/form-data" action="{% url batchimport_import_start %}" method="POST">
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>

</body>
</html>
